server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
#        server-addr: 8.134.163.31:8848 #配置Nacos地址
         server-addr: 192.168.10.100:1111
management:
  endpoints:
    web:
      exposure:
        include: '*'

